### ISSUE TITLE
[Not an issue] Release v4?

### ISSUE THREAD

**Issue by didacrios** [phpList/phpList#6]
Just ask if you have planned any release of the new version or still in a early development.

Thanks for all

**Comment by michield** [comment]
There's nothing planned yet. We're trying to seed community interest :-)

**Comment by tarekdj** [comment]
@michield I'm working on implementing some extra features to pL4. Nothing official yet, just a proof of concept. It should be ready for a demo in a week. Can we plan a core team meeting ?

**Comment by preexo** [comment]
community interest: +1
Is there a "how can I help" page or something which I haven't found yet?

**Comment by michield** [comment]
You can help by making a "how can I help" doc :-) 

But seriously, I hope to be able to dig into it soon and be able to answer that question. In the meantime, try installing the RestAPI plugin and activating the "restapi2" version of it. That one uses the phpList4 codebase and this will be the route to go. Basically, the rest-api2 as the basis for all functionality, so that phpList can be plugged into any system that needs campaign-like emails to be sent.

**Comment by liayn** [comment]
@michield 
> Basically, the rest-api2 as the basis for all functionality, so that phpList can be plugged into any system that needs campaign-like emails to be sent.

This sounds very promising and I would like to have this integrated into TYPO3 as an extension, bringing a modern replacement to good old "direct_mail" extension into the game.

**Comment by michield** [comment]
That would be a great idea!. That's the kind of thing we'd be looking for. I think that makes sense from all angles.

**Comment by oliverklee** [comment]
I have entered #24 for tracking the release of V4 and propose to close this ticket in favor of #24.
